name: Daily S3 Object List PR

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  run-s3-list:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils

      - name: Run S3 list script
        run: |
          ./list_s3_objects.sh https://gov-csv-export-public.s3.ap-northeast-1.amazonaws.com "" gov-csv-export-public

      - name: Create Pull Request if changes exist
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            # Process when changes are detected
            current_date=$(date '+%Y-%m-%d')
            branch_name="update-s3-list-${current_date}"

            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'

            git checkout -b $branch_name
            git add .
            git commit -m "update: S3 object list update ${current_date}"
            git push origin $branch_name

            gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
            gh pr create \
              --title "S3 object list update ${current_date}" \
              --body "Automated update by GitHub Actions" \
              --base main \
              --head $branch_name
          fi